-- Populate Workspace
INSERT INTO Workspace(WKS_NAME) VALUES('MyWorkspace');

-- Populate Ideas
INSERT INTO Idea(IDA_NAME, IDA_DESCRIPTION, IDA_RATING, IDA_FEASIBILITY, IDA_WKS_ID) VALUES('Change it?#1', 'Change it?#1', 3, 'NORMAL', 1);
INSERT INTO Idea(IDA_NAME, IDA_DESCRIPTION, IDA_RATING, IDA_FEASIBILITY, IDA_WKS_ID) VALUES('Change it?#2', 'Change it?#2', 4, 'NORMAL', 1);
INSERT INTO Idea(IDA_NAME, IDA_DESCRIPTION, IDA_RATING, IDA_FEASIBILITY, IDA_WKS_ID) VALUES('Change it?#3', 'Change it?#3', 5, 'NORMAL', 1);